#sudo: required
#dist: trusty

language: node_js
node_js:
  - stable

before_script:
  - python -m SimpleHTTPServer &
  - sleep 2

cache:
  directories:
    - node_modules

addons:
  sauce_connect:
    username: "maarten1234"
    access_key: "a5b54d53-3cfb-4609-a883-e7fa7520afe5"

notifications:
  email: false

